default: fx

shadow: compile
	java Pong ShadowBall 10 true

diamond: compile
	java Pong DiamondBall 10 true

fx: compile
	java Pong FxBall 10 true

regular: compile
	java Pong Ball 10 true

compile:
	javac *.java